log_level = "INFO"

[bot]
command_prefix = "/"
status = "online"
activity = "Testing new features"

[llm]
model = "gemma-4-31b-it"
message_count = 30
system_prompt_path = "prompts/system.xml"

[links]
"twitter.com" = { swap = "fxtwitter.com", clean = true, chat = true }
"x.com" = { swap = "fxtwitter.com", clean = true, chat = true }
"instagram.com" = { swap = "kkinstagram.com", clean = true, chat = true }
"reddit.com" = { swap = "rxddit.com", clean = true, chat = true }
"tiktok.com" = { swap = "d.tiktokez.com", follow = true, clean = true, chat = true }
"youtube.com" = { clean = true, clean_exceptions = ["t", "v"] }
"*" = { clean = true }
